name: 'build-test'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main
      - 'releases/*'
jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: hello
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          syncBranches: 'pre-master'
      - name: Get the headBranch
        run: echo "The time was ${{ steps.hello.outputs.headBranch }}"
